project:
  type: website
  output-dir: docs

website:
  title: "PSInet"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - join.qmd
      - submit.qmd
      - data_terms.qmd
      - events.qmd
      - posts.qmd
      - contact.qmd

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

