---
title: "Submit Data"
toc-location: left
---

PSInet is a global water potential network designed to close knowledge gaps surrounding the water potential gradients that drive ecosystem water flows and govern many aspects of plant function. As part of that work, we are building an open-access database for time series of plant water potential collected in field research settings, including both discrete measurements made with pressure chambers and continuous measurements enabled by psychrometer or tensiometers.  

## Pre-submission survey

By filling out this survey, you are indicating your interest in sharing plant water potential timeseries data, probably collected using a pressure chamber approach, to the database. The database will be published as an open-access tool (e.g. CC-By-4.0 license). Sharing data by XX-XX-XXXX will make you eligible to co-author a network-level data publication (up to two personnel per site) and will give you and your team members priority access to the entire database during a one-year embargo period prior to publication of the data paper. PSInet can also work with you to provide a site-specific DOI for your dataset if desired. Data providers will be given priority access to other network activities, including workshops, conference meet-ups, and some sites may find that sharing data opens the door to future synthesis projects. 

After you fill out this survey, which we anticipate will take you about 15 minutes, you will receive more detailed instructions about how to prepare your data for submission using a standardized .csv template. PSInet will also be holding online help sessions (datathons) to provide additional instructions and to answer questions. 

```{=html}
<iframe id = "presub_survey" src = "https://viz.datascience.arizona.edu/PSInet_presubmission_survey/" style="border: none; width: 100%; height: 720px" frameborder="0"></iframe>
```